kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  labels:
    type: local
    app: test-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"